describe('create New Task', () => {
    beforeEach(function () {
        cy.viewport(1680, 1050)
        cy.internalLogin()
        cy.wait(2000)
        cy.visit('https://workshop.dev.homee.com/jobs')
    })
    it('Add New Tasks from My Task', () => {
        cy.contains('Tasks').click()
        cy.contains('My Tasks').click()
        cy.contains('Add Task').click()
        cy.get('#taskType').type('To Do{enter}')
        cy.get('input[name="title"]').type('New Task added via my Tasks and will link a Claim number')
        cy.get('#detailTask').type('Claim detail information has been entered via automation')
        cy.get('#dueDate').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#dueTime').type('3:30 pm{enter}')
        cy.get('#claim-number').type('GS-000185-2')
        cy.wait(2000)
        cy.get('#claim-number').type(' {enter}')
        cy.screenshot('myTaskClaim')
        cy.contains('Save').click()
        cy.get('button.jsx-294498644 > svg').click()
        cy.wait(2000)
        cy.get('#filter-due-date-filter').click()
        cy.get('.CalendarDay__today').click()
        cy.wait(2000)
        cy.get('.jsx-3475147219.open > .dropdown-wrapper > .jsx-2639819753 > .primary > span').click({force: true})
        cy.wait(2000)
        cy.screenshot('taskOneCreated')
    })
    it('Add New Task from Company Tasks', () => {
        cy.contains('Tasks').click()
        cy.contains('Company Tasks').click()
        cy.contains('Add Task').click()
        cy.get('#taskType').type('Call{enter}')
        cy.get('input[name="title"]').type('New Task added via Company Tasks and will link a Job ID.')
        cy.get('#detailTask').type('Claim detail information has been entered via automation')
        cy.get('#dueDate').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#dueTime').type('3:45 pm{enter}')
        cy.get('#job-number').type('PKKY5CYF')
        cy.wait(2000)
        cy.get('#job-number').type(' {enter}')
        cy.screenshot('companyTaskjob')
        cy.contains('Save').click()
        cy.wait(2000)
        cy.get('button.jsx-294498644 > svg').click()
        cy.get('#filter-due-date-filter').click()
        cy.get('.CalendarDay__today').click()
        cy.wait(2000)
        cy.get('.jsx-3475147219.open > .dropdown-wrapper > .jsx-2639819753 > .primary > span').click({force: true})
        cy.wait(2000)
        cy.screenshot('taskTwoCreated')
    })
    it('Add New Task from Company Tasks', () => {
        cy.contains('Tasks').click()
        cy.contains('Company Tasks').click()
        cy.contains('Add Task').click()
        cy.get('#taskType').type('Call{enter}')
        cy.get('input[name="title"]').type('New Task added to later be deleted.')
        cy.get('#detailTask').type('Automated Task created to test deletion of a task')
        cy.get('#dueDate').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#dueTime').type('4:00 pm{enter}')
        cy.contains('Save').click()
        cy.wait(2000)
        cy.get('button.jsx-294498644 > svg').click()
        cy.get('#filter-due-date-filter').click()
        cy.get('.CalendarDay__today').click()
        cy.wait(2000)
        cy.get('.jsx-3475147219.open > .dropdown-wrapper > .jsx-2639819753 > .primary > span').click({force: true})
        cy.wait(2000)
        cy.screenshot('taskThreeCreated')
    })
})
