describe('Adjuster claim Testing', () => {
     beforeEach(function () {
          cy.viewport(1680, 1050)
          cy.adjusterLogin()  
     })
     it('Create General Claim assignment as adjuster for Decline', () => {
          const claimID = '0000004' 
          cy.wait(2000)
          cy.visit('https://workshop.dev.homee.com/claims')
          cy.contains('Add Claim').click()
          cy.get('h1').should('contain', 'Create Claim')
          cy.get('#adjuster').should('contain', 'Adjuster Smith')
          cy.get('#insuranceCompany').should('contain', 'Anew')
          //Complete all Fields on the form
          cy.get('#claimNumber').type('AUD-')
               .type(claimID)
          cy.get('#referralType').type('General{enter}')
          cy.get('#dateOfLoss').click()
          cy.get('.CalendarDay__today').click()
          cy.get('#fnolDate').click()
          cy.get('.CalendarDay__today').click()
          cy.get('.fnol-time-picker').type('12:00 am{enter}')
          cy.get('#lossDetailsNote').type('These are automated loss detail notes entery via a cypress test.')
          cy.get('[name="insured.emailAddress"]').scrollIntoView
          cy.get('[name="insured.emailAddress"]').type('homeegarysmith+con1@gmail.com')
          cy.get('[name="insured.firstName"]').type('Automation')
          cy.get('[name="insured.lastName"]').type('Testing')
          cy.get('[name="insured.phoneNumber"]').type('5135551234')
          cy.get('#address').type('9648 Conner Ct{enter}')
          cy.wait(1000)
          cy.get('#address').type(',{enter}')
          cy.get('#coverageConcerns').type('Automated notes entered in for Coverage concerns.')
          cy.get('#deductibleAmount').type('1000')
          cy.contains('Payment Breakdown').click()
          .type('Automated text entered for the Payment Breakdown field. This field does not have an id associated to it so we had to identify with the field title.')
          cy.get('[type="submit"]').click()
          //Confirm that new Claims is created
          cy.get('div.jsx-294498644').should('contain.text', 'Claim has been added successfully.')
          cy.get('button.jsx-294498644 > svg > path').click()
    }) 
    it('Create General Claim assignment as adjuster for Acceptance', () => {
          const claimID = '0000004' 
          cy.wait(2000)
          cy.visit('https://workshop.dev.homee.com/claims')
          cy.contains('Add Claim').click()
          cy.get('h1').should('contain', 'Create Claim')
          cy.get('#adjuster').should('contain', 'Adjuster Smith')
          cy.get('#insuranceCompany').should('contain', 'Anew')
          //Complete all Fields on the form
          cy.get('#claimNumber').type('AUA-')
               .type(claimID)
          cy.get('#referralType').type('General{enter}')
          cy.get('#dateOfLoss').click()
          cy.get('.CalendarDay__today').click()
          cy.get('#fnolDate').click()
          cy.get('.CalendarDay__today').click()
          cy.get('.fnol-time-picker').type('12:00 am{enter}')
          cy.get('#lossDetailsNote').type('These are automated loss detail notes entery via a cypress test.')
          cy.get('[name="insured.emailAddress"]').scrollIntoView
          cy.get('[name="insured.emailAddress"]').type('homeegarysmith+con1@gmail.com')
          cy.get('[name="insured.firstName"]').type('Automation')
          cy.get('[name="insured.lastName"]').type('Testing')
          cy.get('[name="insured.phoneNumber"]').type('5135551234')
          cy.get('#address').type('9648 Conner Ct{enter}')
          cy.wait(1000)
          cy.get('#address').type(',{enter}')
          cy.get('#coverageConcerns').type('Automated notes entered in for Coverage concerns.')
          cy.get('#deductibleAmount').type('1000')
          cy.contains('Payment Breakdown').click()
          .type('Automated text entered for the Payment Breakdown field. This field does not have an id associated to it so we had to identify with the field title.')
          cy.get('[type="submit"]').click()
          //Confirm that new Claims is created
          cy.get('div.jsx-294498644').should('contain.text', 'Claim has been added successfully.')
          cy.get('button.jsx-294498644 > svg > path').click()
}) 
     it('Create Emergency Claim assignment as adjuster for Cancellation', () => {
          const claimID = '0000004' 
          cy.wait(2000)
          cy.visit('https://workshop.dev.homee.com/claims')
          cy.contains('Add Claim').click()
          cy.get('h1').should('contain', 'Create Claim')
          cy.get('#adjuster').should('contain', 'Adjuster Smith')
          cy.get('#insuranceCompany').should('contain', 'Anew')
          //Complete all Fields on the form
          cy.get('#claimNumber').type('AUC-')
               .type(claimID)
          cy.get('#referralType').type('Emergency{enter}')
          cy.get('#dateOfLoss').click()
          cy.get('.CalendarDay__today').click()
          cy.get('#fnolDate').click()
          cy.get('.CalendarDay__today').click()
          cy.get('.fnol-time-picker').type('12:00 am{enter}')
          cy.get('#lossDetailsNote').type('These are automated loss detail notes entery via a cypress test.')
          cy.get('[name="insured.emailAddress"]').scrollIntoView
          cy.get('[name="insured.emailAddress"]').type('homeegarysmith+con1@gmail.com')
          cy.get('[name="insured.firstName"]').type('Automation')
          cy.get('[name="insured.lastName"]').type('Testing')
          cy.get('[name="insured.phoneNumber"]').type('5135551234')
          cy.get('#address').type('9648 Conner Ct{enter}')
          cy.wait(1000)
          cy.get('#address').type(',{enter}')
          cy.get('#coverageConcerns').type('Automated notes entered in for Coverage concerns.')
          cy.get('#deductibleAmount').type('1000')
          cy.contains('Payment Breakdown').click()
          .type('Automated text entered for the Payment Breakdown field. This field does not have an id associated to it so we had to identify with the field title.')
          cy.get('[type="submit"]').click()
          //Confirm that new Claims is created
          cy.get('div.jsx-294498644').should('contain.text', 'Claim has been added successfully.')
          cy.screenshot('claimCreated')
          cy.get('button.jsx-294498644 > svg > path').click()
     }) 
})
