describe('Schedule amd Reschedule Estimate', () => {
    beforeEach(function () {
        cy.viewport(1680, 1050)
        cy.internalLogin()
        const claimID = 'AUA-0000004'
        cy.wait(2000)
        cy.visit('https://workshop.dev.homee.com/claims')
        cy.contains(claimID).click({force: true})
        cy.get('h1').should('include.text', claimID)
    })
    it('Schedule Estimate', () => {
        cy.contains('Estimate Scheduled').click()
        cy.get('#scheduled-on-date').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#scheduled-on-time').type('9:00 am{enter}')
        cy.get('#scheduled-for-time').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#scheduled-for-time > .css-1wh42bc-control > .css-1hwfws3').type('9:15 AM{enter}')
        cy.get('label.jsx-1893445797 > .jsx-1893445797').type('Automation notes for Estimate Scheduled')
        cy.contains('Update Status').click()
        cy.get('button.jsx-294498644 > svg > path').click()
        cy.get('h2').should('include.text', 'Estimate Scheduled')
        cy.screenshot('estimateScheduled')
    })
    it('Reschedule Estimate', () => {
        cy.contains('Estimate Rescheduled').click()
        cy.get('#scheduled-on-date').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#scheduled-on-time').type('9:20 am{enter}')
        cy.get('#scheduled-for-time').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#scheduled-for-time > .css-1wh42bc-control > .css-1hwfws3').type('9:30 AM{enter}')
        cy.get('label.jsx-1893445797 > .jsx-1893445797').type('Automation notes for Estimate Rescheduled')
        cy.contains('Update Status').click()
        cy.get('button.jsx-294498644 > svg > path').click()
        cy.get('h2').should('include.text', 'Estimate Scheduled')
        cy.screenshot('rescheduleEstimate')
    })
})