describe('Insured Contacted', () => {
    beforeEach(function () {
        cy.viewport(1680, 1050)
        cy.internalLogin()
        const claimID = 'AUA-0000004'
        cy.wait(2000)
        cy.visit('https://workshop.dev.homee.com/claims')
        cy.contains(claimID).click({force: true})
        cy.get('h1').should('include.text', claimID)
    })
    it('Attempt To Contact Insured', ()=> {
        cy.contains('Contacted Insured').click()
        cy.contains('Select').click()
        cy.get('#react-select-outcome-option-1').click()
        cy.get('#contacted-date').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#contacted-time').type('8:00 am{enter}')
        cy.get('label.jsx-1893445797 > .jsx-1893445797').type('Automated Not Contacted test')
        cy.get('input[name="futureAction"]').type('Future Action data entered via automation')
        cy.get('#follow-up-date').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#follow-up-time').type('8:15 AM{enter}')
        cy.contains('Update Status').click()
        cy.get('button.jsx-294498644 > svg > path').click()
        cy.get('h2').should('include.text', 'Contact Attempted')
        cy.screenshot('attemptedContact')
    })
    it('Contact Insured', ()=> {
        cy.contains('Contacted Insured').click()
        cy.contains('Select').click()
        cy.wait(5000)
        cy.get('#react-select-outcome-option-0').click()
        cy.get('#contacted-date').click()
        cy.get('.CalendarDay__today').click()
        cy.get('#contacted-time').type('8:15 am{enter}')
        cy.get('label.jsx-1893445797 > .jsx-1893445797').type('Automated Insured Contacted test')
        cy.get('input[name="futureAction"]').type('Future action added during insured contacted')
        cy.contains('Update Status').click()
        cy.get('button.jsx-294498644 > svg > path').click()
        cy.get('h2').should('include.text', 'Insured Contacted')
        cy.screenshot('insuredContacted')
    })
})